version: '3.1'
services:

  web:
    image: node
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - API=http://localhost/api
    entrypoint: node
    command: [ "webserver.js","4000"]

  api1:
    image: node
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: node
    command: [ "apiserver.js","3000"]

  api2:
    image: node
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: node
    command: [ "apiserver.js","3000"]
    
  proxy:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro